name: CloudFormation Action

on:
  push:
    branches: [ main ]
    paths:
      - 'cloudformation/cloud_formation_pipeline.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Check Stack
      id: check_stack
      run: |
        if aws cloudformation describe-stacks --stack-name cloud-formation-pipeline; then
          echo "::set-output name=stack_exists::true"
        else
          echo "::set-output name=stack_exists::false"
        fi

    - name: Create or Update Stack
      run: |
        if [ "${{ steps.check_stack.outputs.stack_exists }}" == "true" ]; then
          aws cloudformation create-change-set --stack-name cloud-formation-pipeline \
            --change-set-name my-changeset \
            --template-body file://cloudformation/cloud_formation_pipeline.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameters ParameterKey=BucketNameapi,ParameterValue=${{ secrets.BucketNameapi }} \
              ParameterKey=layerbucketname,ParameterValue=${{ secrets.layerbucketname }} \
              ParameterKey=requestslayername,ParameterValue=${{ secrets.requestslayername }} \
              ParameterKey=pytzlayername,ParameterValue=${{ secrets.pytzlayername }} \
              ParameterKey=repositoryname,ParameterValue=${{ secrets.repositoryname }} \
              ParameterKey=clustername,ParameterValue=${{ secrets.clustername }} \
              ParameterKey=runtimename,ParameterValue=${{ secrets.runtimename }} \
              ParameterKey=Timeout,ParameterValue=${{ secrets.Timeout }} \
              ParameterKey=MemorySize,ParameterValue=${{ secrets.MemorySize }} \
              ParameterKey=TaskCpu,ParameterValue=${{ secrets.TaskCpu }} \
              ParameterKey=TaskMemory,ParameterValue=${{ secrets.TaskMemory }} \
              ParameterKey=startingdate,ParameterValue=${{ secrets.startingdate }} \
              ParameterKey=EndDate,ParameterValue=${{ secrets.EndDate }} \
              ParameterKey=Schedule,ParameterValue=${{ secrets.Schedule }} \
              ParameterKey=restapiname,ParameterValue=${{ secrets.restapiname }} \
              ParameterKey=snowflakeiamarn,ParameterValue=${{ secrets.snowflakeiamarn }} \
              ParameterKey=snowflakeexternalid,ParameterValue=${{ secrets.snowflakeexternalid }}
          aws cloudformation execute-change-set --stack-name cloud-formation-pipeline --change-set-name my-changeset
        else
          aws cloudformation create-stack --stack-name cloud-formation-pipeline \
            --template-body file://cloudformation/cloud_formation_pipeline.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameters ParameterKey=BucketNameapi,ParameterValue=${{ secrets.BucketNameapi }} \
              ParameterKey=layerbucketname,ParameterValue=${{ secrets.layerbucketname }} \
              ParameterKey=requestslayername,ParameterValue=${{ secrets.requestslayername }} \
              ParameterKey=pytzlayername,ParameterValue=${{ secrets.pytzlayername }} \
              ParameterKey=repositoryname,ParameterValue=${{ secrets.repositoryname }} \
              ParameterKey=clustername,ParameterValue=${{ secrets.clustername }} \
              ParameterKey=runtimename,ParameterValue=${{ secrets.runtimename }} \
              ParameterKey=Timeout,ParameterValue=${{ secrets.Timeout }} \
              ParameterKey=MemorySize,ParameterValue=${{ secrets.MemorySize }} \
              ParameterKey=TaskCpu,ParameterValue=${{ secrets.TaskCpu }} \
              ParameterKey=TaskMemory,ParameterValue=${{ secrets.TaskMemory }} \
              ParameterKey=startingdate,ParameterValue=${{ secrets.startingdate }} \
              ParameterKey=EndDate,ParameterValue=${{ secrets.EndDate }} \
              ParameterKey=Schedule,ParameterValue=${{ secrets.Schedule }} \
              ParameterKey=restapiname,ParameterValue=${{ secrets.restapiname }} \
              ParameterKey=snowflakeiamarn,ParameterValue=${{ secrets.snowflakeiamarn }} \
              ParameterKey=snowflakeexternalid,ParameterValue=${{ secrets.snowflakeexternalid }}
        fi